---
title: "IC2S2 '25 Worksheet"
author: Matt Turner
bibliography: ic2s2-2025.bib
---

This worksheet has problem sets and guidance for developing models of social diffusion for use in designing sustainability interventions from empirically-motivated first principles of social cognition and social processes.

## Outline

1.  Installation
2.  Fundamentals of agent-based modeling in R
3.  Agent-based models of adaptation diffusion
4.  Classes in R ([R6 docs](https://r6.r-lib.org/articles/Introduction.html),\
    [R6 Chapter in Hadley Wickham's *Advanced R*](https://adv-r.hadley.nz/r6.html))
5.  Adaptive social learning: success-biased and conformity/frequency-biased learning
6.  Cooperative conservation

## Installation

Install `socmod` from GitHub like so

```{r}
#| output: false
# devtools::install_github("css4s/socmod")
```

## Fundamentals of agent-based modeling in R

Agent-based modeling is useful because one needs only to specify how agents interact with one another, and how their environment changes, to fully specify a social agent-based model of behavior diffusion. There are some tools in R that make this much easier, and on which my `socmod` library is based.

First, there's R6, which provides an API for defining custom classes, e.g., to define how Agent, Model, and other socmod API components work. For example, one must specify what *attributes* agents have, what *processes* they are capable of, and how their attributes affect their choices. Agents are *autonomous*. They make their own decisions based on what they learn from experience and from social observation or learning.

R6 classes have *fields*, which can be used to represent attributes, and *methods*, which are functions or behaviors that instances of the class can do. For example, the Agent class provided by `socmod` has fields representing its behavior and its *fitness*, which is an abstraction for apparent wealth, skills, happiness, or other features that could make the person an attractive teacher.

See the R script `R/fundamentals.R` for some demonstrations of **functional programming** and **defining custom classes in R**. We make extensive use of functional programming in agent-based modeling because we provide *rules* in the form of software *functions* that exist independently of models or agents. It is not just `socmod`: NetLogo, one of if not the most widely used open source agent-based modeling software packages is essentially a functional programming language that evolved from other functional programming languages from some decades ago.

### Exercise:

Create a set of custom class to represent something related to your research, your hobbies, etc. For another example beyond the football one, one student in my course this year created a `Forest` class that had a `trees` field, which was an R list of instances of another class called `Tree`. A `Forest` could track recent rainfall or the spread of pests like the pine bark beetle that loves to infest dried out trees in western North America, exacerbating the risk of catastrophic wildfires due to frequent droughts. Feel free to make your own version of the Tree and Forest classes, or extend the football example from the Notes.

## Contagion-based learning: a first example

Before diving in to details, let's see agent-based contagion diffusion in action. In `socmod` we provide `partner_selection` and `interaction` learning rules, plus optionally a `model_step`, and a label for the dynamics that you specify. Let's create some agents and use contagion learning for

## Formal models of behavior diffusion

The prevalence dynamics that guided the design of agent-based models have *formal*, i.e., *mathematical*, versions that use calculus to gain insight into what strategies might work best in which situations, and which should be avoided. One surprising result so far is that conformity is mostly a weak driver of adaptation diffusion compared to success-biased learning. Conformity has been intensely studied over several decades as an explanation for the explosion of human culture. New models of conformity examine its sometimes exotic dynamics due to its non-linearity with some non-human studies supporting this including fish and birds.

Using this formal approach, we can provide some reasons why *human* culture likely did not exclusively, or even extensively, rely on conformity as its main drive. We know of no other intelligent being, biological or artificial, that can match human capacity for information integration, exploration, and complex actions [@Witt2024]. Specifically, I showed that conformity is significantly weaker during the critical period of *entrenchment onset* compared to success-biased learning, which provides relatively strong selection signals for learners throughout the diffusion process. I also showed that at the very earliest stages of diffusion that success-biased diffusion is stronger, but that anti-conformity can rapidly provide strong selection signals after a non-trivial prevalence threshold has been reached. But, again, once the adaptation starts reaching entrenchment onset, conformity-based selection rapidly loses its strength.

To make this more concrete, recall that as prevalence increases towards $a = 0.5$ under anti-conformity ($\gamma < 0$), the rate of change of prevalence $\dot a$ is positive but rapidly approaches 0. At $a = 0.5$, $\dot a$ *is* zero no matter the value of $\gamma$. If somehow $a$ continued past $a = 0.5$ but with $\gamma < 0$, this would make $\dot a < 0$, which would cause diffusion to a halt at $a = 0.5$, or possibly oscillate around this value depending on other contextual factors [@Denton2020].

For this part:

1.  First, what happens when $\gamma = 0$? Why?
2.  Plot the diffusion rate over $a$ for a few different values of $\pm \gamma$ (e.g., $\gamma = \pm 0.2, \pm 1$, or $\gamma = 0$. Explain what happens around $a=0.5$ (e.g., from $a = 0.25$ to $a = 0.75$, where conformity effects get increasingly weak and then change sign.
3.  Explain how this supports understanding the derivation of limiting cases for $\dot a(a = 0.5 \pm \epsilon)$, i.e., the rate of change of adoption just before and after entrenchment onset. See Equations X.X - X.Y in the notes for these limiting cases.

## Cooperative conservation

In the chapter on cooperative conservation, we developed both a geometric game theory analysis and agent-based model of the evolution of cooperation on a spatial grid. This has applications to

## More exercises

1.  In this exercise I invite you to examine, critique, or reimagine some work I've begun to predict how many men must choose to follow women in order to break old norms that socially or economically sanctioned men who were observed to be following women. You can find this work at <https://github.com/CSS4S/gender-role-inversion>.\
    \
    This work has been inspried by the work of computational social scientist and philosopher of science Prof. Cailin O'Connor, at University of California, Irvine. She has demonstrated that inequality and unfairness can persist even if the conditions are removed that initially caused the inequality [@OConnor2019Origins], and that minority groups can find themselves especially at risk for suffering inequality [@Mohseni2021]. For example, even though the gender wage gap is closing, professional women often find themselves burdened with an unreasonable amount of domestic chores, even when they are the primary breadwinner [@OConnor2019-magazine].
